import StyleIndex from "@/components/graphics/StyleIndex";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cenník – LingoLab",
  description: "Generated by create next app",
};

export default function Pricelist() {
  return (
    <div className="px-4 mb-24">
      <StyleIndex />
      <section
        id="cenova-ponuka"
        className="relative container mx-auto max-w-7xl flex justify-center flex-col mb-12 md:mb-0"
      >
        <h1 className="text-3xl mb-8 font-extrabold sm:text-5xl sm:leading-[3.5rem] text-balance">
          Cenník
        </h1>
      </section>
    </div>
  );
}
