import StyleIndex from "@/components/graphics/StyleIndex";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog – LingoLab",
  description: "Generated by create next app",
};
export default function Blog() {
  return (
    <div className="px-4 mb-24">
      <StyleIndex />
      <section
        id="blog"
        className="relative container mx-auto max-w-7xl flex justify-center flex-col mb-12 md:mb-0"
      >
        blog
      </section>
    </div>
  );
}
