import StyleIndex from "@/components/graphics/StyleIndex";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Meno lektora – LingoLab",
  description: "Generated by create next app",
};

export default function Lecturer() {
  return (
    <div className="px-4 mb-24">
      <StyleIndex />
      <section
        id="pribeh"
        className="relative container mx-auto max-w-7xl flex justify-center flex-col mb-12 md:mb-0"
      >
        <h1 className="text-3xl mb-8 font-extrabold sm:text-5xl sm:leading-[3.5rem] text-balance">
          {/* <img src="/" alt="" /> */}
          Peter Marcin
        </h1>
        <div className="grid lg:grid-cols-2 mt-2 gap-x-4">
            
        </div>
      </section>
    </div>
  );
}
