import StyleIndex from "@/components/graphics/StyleIndex";
import ClubCard from "@/components/util/ClubCard";
import CourseListing from "@/components/util/CourseListing";
import Details from "@/components/util/Details";
import LectureOffer from "@/components/util/LectureOffer";
import { IconZoomQuestion } from "@tabler/icons-react";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Kurzy – LingoLab",
  description: "Generated by create next app",
};

export default function Courses({
  courses = {
    title: "Doučovanie",
    list: [
      {
        title: "Angličtina",
        flag: "GB",
        price: 15,
        slug: "anglictina",
        mentors: [
          {
            fullName: "Leslie Alexander",
            image:
              "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
          {
            fullName: "Michael Foster",
            image:
              "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
          {
            fullName: "Dries Vincent",
            image:
              "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80",
          },
          {
            fullName: "Lindsay Walton",
            image:
              "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Nemčina",
        flag: "DE",
        price: 20,
        slug: "nemcina",
        mentors: [
          {
            fullName: "Courtney Henry",
            image:
              "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Francúzština",
        flag: "FR",
        price: 25,
        slug: "francuzstina",
        mentors: [
          {
            fullName: "Dries Vincent",
            image:
              "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Španielčina",
        flag: "ES",
        price: 30,
        slug: "spanielcina",
        mentors: [
          {
            fullName: "Lindsay Walton",
            image:
              "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Taliančina",
        flag: "IT",
        price: 35,
        slug: "taliancina",
        mentors: [
          {
            fullName: "Michael Foster",
            image:
              "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
    ],
  },
  preps = {
    title: "Príprava na maturitu",
    list: [
      {
        title: "Španielčina",
        flag: "ES",
        price: 30,
        slug: "spanielcina",
        mentors: [
          {
            fullName: "Lindsay Walton",
            image:
              "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Taliančina",
        flag: "IT",
        price: 35,
        slug: "taliancina",
        mentors: [
          {
            fullName: "Michael Foster",
            image:
              "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
    ],
  },
  groups = {
    title: "Konzervačné hodiny",
    list: [
      {
        title: "Španielčina",
        flag: "ES",
        price: 30,
        slug: "spanielcina",
        mentors: [
          {
            fullName: "Lindsay Walton",
            image:
              "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
      {
        title: "Taliančina",
        flag: "IT",
        price: 35,
        slug: "taliancina",
        mentors: [
          {
            fullName: "Michael Foster",
            image:
              "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
          },
        ],
      },
    ],
  },
  faq = [
    {
      question: "Ako sa môžem prihlásiť na kurz?",
      answer:
        'Prihlásiť sa môžete jednoducho cez našu webovú stránku. Vyberte si kurz, ktorý vás zaujíma a kliknite na tlačidlo "Prihlásiť sa".',
    },
    {
      question: "Koľko trvá jeden kurz?",
      answer:
        "Čas trvania kurzu závisí od jeho náročnosti a vašich cieľov. V priemere trvá jeden kurz 3 mesiace.",
    },
    {
      question: "Koľko stojí jeden kurz?",
      answer:
        "Cena kurzu závisí od jeho náročnosti a jazyka, ktorý sa učíte. Priemerná cena kurzu je 20 € za hodinu.",
    },
    {
      question: "Koľko lektorov máte?",
      answer:
        "V našej jazykovej škole máme viac ako 10 lektorov, ktorí vám radi pomôžu s výberom kurzu a úrovne.",
    },
  ],
}) {
  return (
    <div className="px-4">
      <StyleIndex />
      <section
        id="zoznam"
        className="relative container mx-auto max-w-7xl flex justify-center flex-col mb-12 md:mb-0"
      >
        <div className="mt-2">
          <h1 className="text-3xl mb-8 font-extrabold sm:text-5xl sm:leading-[3.5rem] text-balance">
            Dostupné kurzy
          </h1>
        </div>

        <div className="relative grid lg:lg:grid-cols-[minmax(540px,_1fr)_minmax(480px,520px)] gap-x-4">
          <div className="md:mb-12">
            <CourseListing course={courses} />
            <CourseListing course={preps} />
            <CourseListing course={groups} />
          </div>
          <div className="relative h-[calc(100%-6rem)]">
            <div className="sticky md:top-36 md:mt-12">
              <LectureOffer className="p-8 bg-slate-100 rounded-lg" />
              <Link
                href="#faq"
                className="group flex items-center gap-2 w-full mt-2 p-4 px-8 text-slate-700 border border-slate-300 rounded-lg hover:bg-slate-50 transition-all"
              >
                <IconZoomQuestion
                  size={20}
                  className="group-hover:-rotate-180 transition-transform delay-75"
                />
                Často kladené otázky
              </Link>
            </div>
          </div>
        </div>
      </section>
      <ClubCard />
      <section
        id="faq"
        className="relative container mx-auto max-w-7xl flex justify-center flex-col mb-24 pt-24"
      >
        <div className="mb-8">
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl text-center">
            Často kladené otázky
          </h2>
        </div>
        <div className="grid md:  grid-cols-2 gap-4">
          <div>
            {faq.map(({ question, answer }, id) => (
              <Details
                key={question}
                isOpen={id === 0}
                question={question}
                answer={answer}
              />
            ))}
          </div>
          <div>
          {faq.splice(0, 5).map(({ question, answer }, id) => (
              <Details
                key={question}
                isOpen={id === 0}
                question={question}
                answer={answer}
              />
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
